name: Deploy to Vercel

on:
  push:
    branches: [ main, genspark_ai_developer ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Validate HTML
      run: |
        if [ -f "index.html" ]; then
          echo "HTML file exists"
        else
          echo "HTML file not found"
          exit 1
        fi

    - name: Install Vercel CLI
      run: npm install -g vercel

    - name: Deploy to Vercel
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --confirm
        else
          vercel --token ${{ secrets.VERCEL_TOKEN }} --confirm
        fi
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}